### ISSUE TITLE
New Cart Type: Hoover Cart

### ISSUE THREAD

**Issue by anuar2k** [Terasology/AdditionalRails#15]
The Hoover Cart would collect all items and blocks laying on the ground in 3x3 area around the cart. It would have an inventory used to store the collected items and a input space for fuel, which would power the device. One fuel unit would provide energy for collecting for example 50 items/blocks.

This cart could be used together with a tunnel borer cart to collect digged stuff, or in some automated farm to collect the harvest.

This cart would collect these items in a similiar way like the player does.

**Comment by pollend** [comment]
moved to GCI
